import pdb
import pandas as pd
#pdb.set_trace()

#fecha_inicio =  pd.to_datetime('2007020416', format ='%Y%m%d%H', errors='coerce')

#anno_fin='2007', mes_fin='02', dia_fin='05', anno_ini='2007', mes_ini='02', dia_ini='04', hra_ini='06'
#anno_fin, mes_fin, dia_fin, anno_ini, mes_ini, dia_ini, hra_ini
def funcion_fin(anno_fin='2015', mes_fin='08', dia_fin='30', anno_ini='2015', mes_ini='08', dia_ini='28', hra_ini='06'):
    fecha_inicio =  pd.to_datetime(str(anno_ini)+str(mes_ini)+str(dia_ini)+str(hra_ini), format ='%Y%m%d%H', errors='coerce')
    delta = pd.Timedelta(hours=6)
    
    #print(anno_fin)
    for i in [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,18]:
        fecha_fin = fecha_inicio -(delta * i)
        fecha_fin = pd.to_datetime(fecha_fin)
        #print(len(str(fecha_fin.month)))
        fin_anno = str(fecha_fin.year)
        fin_mes = str(fecha_fin.month)
        if len(fin_mes) < 2:
            fin_mes = '0' + fin_mes
        fin_dia = str(fecha_fin.day)
        if len(fin_dia) < 2:
            fin_dia = '0' + fin_dia
        fin_hora = str(fecha_fin.hour)
        if len(fin_hora) < 2:
            fin_hora = '0' + fin_hora
        print(fin_anno, fin_mes, fin_dia, fin_hora)
        
   
        f = open('namelistinput/'+str(i)+'.sh', 'w')
        with open('namelistinput/'+str(i)+'.sh', 'w') as f:
            print('#!/bin/bash', file=f)
            print('mkdir '+str(i)+'_folder', file=f)
            print('cd '+str(i)+'_folder', file=f)
            print('', file=f)
            print('', file=f)
            print('ulimit -s unlimited', file=f)
            print('source /scr/hercules1san/meteoro/edwin/wrf/var_env.sh', file=f)
            print('', file=f)
            print('', file=f)
            print('', file=f)
            print('', file=f)
            print('', file=f)
            print('', file=f)
            print('        echo "&time_control', file=f)
            print('run_days                 = 0,', file=f)
            print('run_hours                = 0,', file=f)
            print('run_minutes              = 0,', file=f)
            print('run_seconds              = 0,', file=f)
            print('start_year               = '+fin_anno+', '+fin_anno+', 00,', file=f)
            print('start_month              = '+fin_mes+',   '+fin_mes+',   00,  ', file=f)
            print('start_day                = '+fin_dia+',   '+fin_dia+',   00,  ', file=f)
            print('start_hour               = '+fin_hora+',   '+fin_hora+',   00,  ', file=f)
            print('start_minute             = 00,   00,   00,  ', file=f)
            print('start_second             = 00,   00,   00,  ', file=f)
            print('end_year                 = '+str(anno_fin)+', '+str(anno_fin)+', '+str(anno_fin)+',', file=f)
            print('end_month                = '+str(mes_fin)+',   '+str(mes_fin)+',   '+str(mes_fin)+',  ', file=f)
            print('end_day                  = '+str(dia_fin)+',   '+str(dia_fin)+',   '+str(dia_fin)+',  ', file=f)
            print('end_hour                 = 00,   00,   00,  ', file=f)
            print('end_minute               = 00,   00,   00,  ', file=f)
            print('end_second               = 00,   00,   00,  ', file=f)
            print('interval_seconds         = 21600,', file=f)
            print('input_from_file          = .true.,   .true.,   .true.,', file=f)
            print('history_interval         = 60,       60,       60,', file=f)
            print('frames_per_outfile       = 1,        1,        1,', file=f)
            print('restart                  = .false.,', file=f)
            print('restart_interval         = 5000,', file=f)
            print('io_form_history          = 2,', file=f)
            print('io_form_restart          = 2,', file=f)
            print('io_form_input            = 2,', file=f)
            print('io_form_boundary         = 2,', file=f)
            print('debug_level              = 0,', file=f)
            print('/', file=f)
            print('', file=f)
            print('&domains                 ', file=f)
            print('time_step                = 60,', file=f)
            print('time_step_fract_num      = 0,', file=f)
            print('time_step_fract_den      = 1,', file=f)
            print('max_dom                  = 2,', file=f)
            print('e_we                     = 100,      148,      448,', file=f)
            print('e_sn                     = 99,      196,      385,', file=f)
            print('e_vert                   = 35,       35,       35,', file=f)
            print('p_top_requested          = 5000,', file=f)
            print('num_metgrid_levels       = 27,', file=f)
            print('num_metgrid_soil_levels  = 4,', file=f)
            print('dx                       = 10000,   3333.334,   1666.667,', file=f)
            print('dy                       = 10000,   3333.334,   1666.667,', file=f)
            print('grid_id                  = 1,        2,        3,', file=f)
            print('parent_id                = 1,        1,        2,', file=f)
            print('i_parent_start           = 1,       25,       33,', file=f)
            print('j_parent_start           = 1,       26,       33,', file=f)
            print('parent_grid_ratio        = 1,        3,        3,', file=f)
            print('parent_time_step_ratio   = 1,        3,        3,', file=f)
            print('feedback                 = 1,', file=f)
            print('smooth_option            = 0,', file=f)
            print('/', file=f)
            print('', file=f)
            print('&physics                 ', file=f)
            print('mp_physics               = 0, 0,', file=f)
            print('ra_lw_physics            = 7,  7, ', file=f)
            print('ra_sw_physics            = 3,  3, ', file=f)
            print('radt                     = 30, 30,30,', file=f)
            print('sf_sfclay_physics        = 91,  91, ', file=f)
            print('sf_surface_physics       = 1,  1, 1, ', file=f)
            print('bl_pbl_physics           = 5,  5, ', file=f)
            print('bldt                     = 0,  0, 0, ', file=f)
            print('cu_physics               = 0,  0, ', file=f)
            print('cudt                     = 5,  5, 5, ', file=f)
            print('isfflx                   = 1,', file=f)
            print('ifsnow                   = 0,', file=f)
            print('icloud                   = 1,', file=f)
            print('surface_input_source     = 1,', file=f)
            print('num_soil_layers          = 4,', file=f)
            print('sf_urban_physics         = 0,  ', file=f)
            print('maxiens                  = 1,', file=f)
            print('maxens                   = 3,', file=f)
            print('maxens2                  = 3,', file=f)
            print('maxens3                  = 16,', file=f)
            print('ensdim                   = 144,', file=f)
            print('/', file=f)
            print('', file=f)
            print('&fdda                    ', file=f)
            print('/', file=f)
            print('', file=f)
            print('&dynamics                ', file=f)
            print('w_damping                = 0,', file=f)
            print('diff_opt                 = 2,', file=f)
            print('km_opt                   = 4,', file=f)
            print('diff_6th_opt             = 0,        ', file=f)
            print('diff_6th_factor          = 0.12,     ', file=f)
            print('base_temp                = 290.,', file=f)
            print('damp_opt                 = 0,', file=f)
            print('zdamp                    = 5000.,    ', file=f)
            print('dampcoef                 = 0.2,     0.2,     0.2,    ', file=f)
            print('khdif                    = 0,       0,       0,      ', file=f)
            print('kvdif                    = 0,       0,       0,      ', file=f)
            print('non_hydrostatic          = .true.,  .true.,  .true., ', file=f)
            print('moist_adv_opt            = 1,       1,       1,      ', file=f)
            print('scalar_adv_opt           = 1,       1,       1,      ', file=f)
            print('/', file=f)
            print('', file=f)
            print('&bdy_control             ', file=f)
            print('spec_bdy_width           = 5,', file=f)
            print('spec_zone                = 1,', file=f)
            print('relax_zone               = 4,', file=f)
            print('specified                = .true.,  .true.,  .true., ', file=f)
            print('nested                   = .false., .false., .false.,', file=f)
            print('/', file=f)
            print('', file=f)
            print('&grib2                   ', file=f)
            print('/', file=f)
            print('', file=f)
            print('&namelist_quilt          ', file=f)
            print('nio_tasks_per_group      = 0,', file=f)
            print('nio_groups               = 1,', file=f)
            print('/" > namelist.input', file=f)
            print('', file=f)
            print('cp /homes/orion/etorresm/Downloads/201508_6_2/met_em* .', file=f)
            print('###', file=f)
            print('', file=f)
            print('ln -s /scr/hercules1san/meteoro/edwin/wrf/wrf/WRFV3/run/* .', file=f)
            print('', file=f)
            print('./real.exe', file=f)
            print('', file=f)
            print('ulimit -s unlimited', file=f)
            print('mpirun -n 5 ./wrf.exe', file=f)
            print('rm met_em.d0*', file=f)
            print('        cd ..', file=f)
            print('', file=f)
            print('#python3.6 ~/Downloads/mail.py &', file=f)

funcion_fin()